#!/bin/sh
set -e

cat <<'EOF' | mysql -u root --password=root
CREATE DATABASE gokv;
USE gokv;
CREATE TABLE IF NOT EXISTS key_values (
			`id` bigint(20) NOT NULL AUTO_INCREMENT,
			`key` varchar(255) NOT NULL,
			`value` blob NOT NULL,
			`created_at` datetime NOT NULL,
			`updated_at` datetime NOT NULL,
			`expires_at` datetime DEFAULT NULL,
			PRIMARY KEY (id),
			UNIQUE KEY index_key_values_on_key (`key`),
			KEY index_key_values_on_expires_at (expires_at)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8
EOF

DRIVERS="
sqlite:
mysql:root:root@tcp(127.0.0.1:3306)/gokv
"

for d in $DRIVERS; do
	export GOKV_DRIVER=$(echo "$d" | cut -d : -f1)
	export GOKV_DSN=$(echo "$d" | cut -d : -f2-)
	go test
done
