#!/bin/sh

trap "rm testdata/sqlite.db; docker-compose down" EXIT
docker-compose up -d

# wait a minute for mysql to start
for i in $(seq 60); do
	if echo -e '\x04' | nc 127.0.0.1 3306 >/dev/null 2>&1; then
		ready=1
		break
	fi
	sleep 1
done

if [ -z "$ready" ]; then
	exit 1
fi

DRIVERS="
sqlite:testdata/sqlite.db
mysql:root:toor@tcp(127.0.0.1:3306)/gokv
"

for d in $DRIVERS; do
	export GOKV_DRIVER=$(echo "$d" | cut -d : -f1)
	export GOKV_DSN=$(echo "$d" | cut -d : -f2-)
	go test
done
