name: build 

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: run integration tests
      run: ./script/ci
