name: build 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Set up MySQL
      run: |
        sudo systemctl start mysql.service
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.17'
    - name: run integration tests
      run: ./script/ci
