name: "Create new release on tag push"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Cut a release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release script
        run: script/release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color

permissions:
  packages: write
  contents: write
